######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 24 14:49:55 2018
######################################################################

TEMPLATE = app
TARGET = inject_call
DEPENDPATH += . src/test
INCLUDEPATH += . src/test
OBJECTS_DIR = build
DESTDIR = build

# Input
HEADERS += src/test/inject_call.h
SOURCES += src/test/inject_call.cpp
